#!/usr/bin/env python
# -*-python-*-

import sys
import os.path
import logging

import mapzen.whosonfirst.utils
import mapzen.whosonfirst.spatial

if __name__ == '__main__':

    import sys
    import optparse

    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-s', '--source', dest='source', action='store', default='None', help='')
    opt_parser.add_option('-d', '--database', dest='database', action='store', default='whosonfirst_pip', help='')
    opt_parser.add_option('-u', '--username', dest='username', action='store', default='postgres', help='')

    # sudo make me use a config file...

    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')
    options, args = opt_parser.parse_args()

    if options.verbose:	
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    dsn = "dbname=%s user=%s" % (options.database, options.username)
    idx = mapzen.whosonfirst.spatial.index(dsn)

    source = os.path.abspath(options.source)
    crawl = mapzen.whosonfirst.utils.crawl(source, inflate=True)

    for feature in crawl:
        logging.debug("import feature %s" % feature.get('id', "UNKNOWN"))
        idx.import_feature(feature)

    sys.exit()
        
